// Tiny Resend client. Sends an email with one or more attachments.
// If RESEND_API_KEY isn't set the caller should skip calling this function.

export interface ResendAttachment {
  filename: string;
  bytes: Uint8Array;
}

export async function sendReportEmail(opts: {
  apiKey: string;
  fromAddress: string;       // e.g. reports@esprey.net (must be on a verified domain)
  toAddress: string;
  replyTo?: string;          // optional — replies route here instead of the from-address
  monthLabel: string;
  attachments: ResendAttachment[];
}): Promise<{ id: string }> {
  const summary = opts.attachments.map((a) => `- ${a.filename}`).join("\n");
  const body: Record<string, unknown> = {
    from: `Esprey Expenses <${opts.fromAddress}>`,
    to: [opts.toAddress],
    subject: `Expense report — ${opts.monthLabel}`,
    text:
      `Your monthly expense report for ${opts.monthLabel} is attached.\n\n` +
      `Attachments:\n${summary}\n\n` +
      `Generated by Esprey Expenses.`,
    attachments: opts.attachments.map((a) => ({
      filename: a.filename,
      content: uint8ToBase64(a.bytes),
    })),
  };
  if (opts.replyTo) body.reply_to = opts.replyTo;
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${opts.apiKey}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Resend ${res.status}: ${txt.slice(0, 500)}`);
  }
  return (await res.json()) as { id: string };
}

/** Welcome email sent to a newly-added team member, in their language. */
export async function sendWelcomeEmail(opts: {
  apiKey: string;
  fromAddress: string;
  toAddress: string;
  replyTo?: string;
  displayName?: string | null;
  addedByName?: string | null;
  appUrl: string;
  language?: "en" | "fr" | "pt";
}): Promise<{ id: string }> {
  const appUrl = opts.appUrl.replace(/\/$/, "") + "/";
  const helpUrl = opts.appUrl.replace(/\/$/, "") + "/instructions";
  const lang = opts.language === "fr" ? "fr" : opts.language === "pt" ? "pt" : "en";
  const firstName = opts.displayName ? opts.displayName.split(" ")[0] : null;

  const SUBJECTS = {
    en: "You've been added to Esprey Expenses",
    fr: "Vous avez été ajouté à Esprey Expenses",
    pt: "Foi adicionado ao Esprey Expenses",
  } as const;
  const BODIES = { en: welcomeEn, fr: welcomeFr, pt: welcomePt } as const;

  const body: Record<string, unknown> = {
    from: `Esprey Expenses <${opts.fromAddress}>`,
    to: [opts.toAddress],
    subject: SUBJECTS[lang],
    ...(opts.replyTo ? { reply_to: opts.replyTo } : {}),
    text: BODIES[lang](firstName, opts.addedByName ?? null, appUrl, helpUrl),
  };
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${opts.apiKey}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Resend ${res.status}: ${txt.slice(0, 500)}`);
  }
  return (await res.json()) as { id: string };
}

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk) as unknown as number[]);
  }
  return btoa(binary);
}


/* ---------------- Welcome email bodies ---------------- */

function welcomeEn(firstName: string | null, addedBy: string | null, appUrl: string, helpUrl: string): string {
  const greeting = firstName ? `Hi ${firstName},` : "Hi,";
  const inviter = addedBy ? ` by ${addedBy}` : "";
  return `${greeting}

You've been added${inviter} to Esprey Expenses, the app we use to capture business expenses and produce monthly invoices for reimbursement.

Keep this email as a reference. Everything below (and more) also lives in the app: tap the "?" on the home screen for the searchable Help & FAQ, where you can also just type a question and get an answer:
${helpUrl}

────────────────────────────
SIGN IN
────────────────────────────

Open this URL in any browser (phone, tablet, computer):
${appUrl}

Cloudflare will email you a 6-digit one-time code the first time. Paste it in, you're done. Sessions last 24 hours; after that you get another code.

Save the app to your home screen so it opens like a native app:
  • iPhone (Safari): tap Share → "Add to Home Screen"
  • Android (Chrome): tap the ⋮ menu → "Install app"

────────────────────────────
WHAT'S PRIVATE TO YOU
────────────────────────────

Your receipts, your monthly reports, your profile and bank details, and your private "people" list are YOURS alone. The admin cannot see any of them.

Shared across the team (admins curate; you see what's assigned to you): companies you can bill to, categories (and their spending limits), and currencies.

────────────────────────────
STEP 1: SET UP YOUR PROFILE
────────────────────────────

Go to Settings → My Profile and fill in:
  • Your app language — English or French. The whole app, and the receipt descriptions the AI writes, follow it.
  • Your full name (and business name if you invoice through one)
  • Address, VAT number (if applicable), phone
  • Bank details — free-form text; paste whatever your bank requires.

This appears at the top of every invoice you generate, so the payer knows who to pay and how.

────────────────────────────
STEP 2: THREE WAYS TO ADD A RECEIPT
────────────────────────────

1) CAMERA — Tap "+ Capture", snap the receipt. Vendor, amount, date and currency are read automatically; you confirm, tag, save.
   Multi-page invoice? After the first photo tap "+ Add another page" — all pages combine into one PDF receipt.

2) FORWARD AN EMAIL — Send any receipt to receipts@esprey.net. Uber confirmations, PDF invoices, photos, text-only emails all work. IMPORTANT: send from THIS address (or a registered alias — see below). Unregistered senders get a bounce-back.

3) MANUAL ENTRY — Tap "+ Manual" for cash with no receipt; amount is required.

Backlog? "+ Capture" → "Pick photo(s) or PDF from files" lets you select many at once — each becomes its own receipt.

────────────────────────────
TAG WHO WAS WITH YOU
────────────────────────────

On any receipt, use "People present" to note who joined (client dinner, shared taxi). Your people list is private, favourites float to the top — and the names now appear next to that expense in the monthly report, so the claim carries its context. Worth doing for every meal.

────────────────────────────
RESTAURANT / TAXI TIPS
────────────────────────────

For Meals or Taxi receipts a Tip field appears: put the BILL amount (as printed) in Amount, pick a tip % or a custom amount, and the app saves Bill + Tip = Total. Your records match what you actually paid, with the printed bill preserved for audit.

────────────────────────────
SPENDING LIMITS
────────────────────────────

Some categories carry a per-receipt limit set by the admin. Go over it and the receipt is flagged — you can still claim it, just tap Acknowledge on the receipt to confirm you know. No sneaking, no blocking; just a record.

────────────────────────────
GENERATING A MONTHLY REPORT
────────────────────────────

At month-end, open Reports:
  1. Pick the month (defaults to last month), optionally one company, optionally a target currency (converted at each receipt's capture-day rate)
  2. Pick the report language — independent of your app language, so you can work in French and hand your accountant an English PDF. Establishment names always stay exactly as printed.
  3. Tap Generate, then choose: Open PDF, Download PDF, or Email PDF. A ZIP of the original files is also there (Download originals / Email ZIP).

Nothing is emailed unless you press an email button.

────────────────────────────
THE "ISSUES" BUTTON
────────────────────────────

The Issues pill on the dashboard turns red when receipts need attention: unreadable photo, missing amount, possible duplicate, edited values that differ from the receipt, or over a spending limit. Open each one — the banner explains exactly why and what to do.

────────────────────────────
DELETED SOMETHING BY MISTAKE?
────────────────────────────

Deleting a receipt moves it to Settings → Trash for 30 days. Restore it from there; after 30 days it's gone for good.

────────────────────────────
MULTIPLE EMAIL ADDRESSES?
────────────────────────────

If you might forward receipts from more than one address (work + personal), reply to this email with the others. They'll be registered as aliases — receipts land in the same account and sign-in works from any of them.

────────────────────────────
HELP
────────────────────────────

In-app Help & FAQ (searchable, with an ask-a-question box): ${helpUrl}
Anything else: just reply to this email.

— Esprey Expenses
`;
}

function welcomeFr(firstName: string | null, addedBy: string | null, appUrl: string, helpUrl: string): string {
  const greeting = firstName ? `Bonjour ${firstName},` : "Bonjour,";
  const inviter = addedBy ? ` par ${addedBy}` : "";
  return `${greeting}

Vous avez été ajouté${inviter} à Esprey Expenses, l'application que nous utilisons pour saisir les dépenses professionnelles et produire les notes de frais mensuelles à rembourser.

Gardez cet e-mail comme référence. Tout ce qui suit (et plus) se trouve aussi dans l'application : touchez le « ? » sur l'écran d'accueil pour l'Aide & FAQ consultable, où vous pouvez aussi simplement poser une question :
${helpUrl}

────────────────────────────
SE CONNECTER
────────────────────────────

Ouvrez cette adresse dans n'importe quel navigateur (téléphone, tablette, ordinateur) :
${appUrl}

Cloudflare vous enverra un code à 6 chiffres par e-mail la première fois. Saisissez-le, c'est terminé. Les sessions durent 24 heures ; ensuite vous recevez un nouveau code.

Ajoutez l'application à votre écran d'accueil pour qu'elle s'ouvre comme une application native :
  • iPhone (Safari) : touchez Partager → « Sur l'écran d'accueil »
  • Android (Chrome) : menu ⋮ → « Installer l'application »

────────────────────────────
CE QUI EST PRIVÉ
────────────────────────────

Vos reçus, vos rapports mensuels, votre profil et vos coordonnées bancaires, et votre liste privée de « personnes » sont à VOUS seul. L'administrateur ne peut voir aucun de ces éléments.

Partagé pour toute l'équipe (géré par l'administrateur ; vous voyez ce qui vous est attribué) : les sociétés facturables, les catégories (et leurs limites de dépense), et les devises.

────────────────────────────
ÉTAPE 1 : CONFIGUREZ VOTRE PROFIL
────────────────────────────

Allez dans Réglages → Mon profil et renseignez :
  • Votre langue — français ou anglais. Toute l'application, et les descriptions de reçus écrites par l'IA, la suivent.
  • Votre nom complet (et raison sociale si vous facturez via une société)
  • Adresse, numéro de TVA (le cas échéant), téléphone
  • Coordonnées bancaires — texte libre ; collez ce que votre banque exige.

Ces informations apparaissent en haut de chaque note de frais que vous générez, pour que le payeur sache qui payer et comment.

────────────────────────────
ÉTAPE 2 : TROIS FAÇONS D'AJOUTER UN REÇU
────────────────────────────

1) PHOTO — Touchez « + Photo », photographiez le reçu. Fournisseur, montant, date et devise sont lus automatiquement ; vous confirmez, étiquetez, enregistrez.
   Facture de plusieurs pages ? Après la première photo, touchez « + Ajouter une page » — toutes les pages sont combinées en un seul reçu PDF.

2) TRANSFÉRER UN E-MAIL — Envoyez n'importe quel reçu à receipts@esprey.net. Confirmations Uber, factures PDF, photos, e-mails texte : tout fonctionne. IMPORTANT : envoyez depuis CETTE adresse (ou un alias enregistré — voir plus bas). Les expéditeurs inconnus reçoivent un rejet.

3) SAISIE MANUELLE — Touchez « + Saisie » pour l'espèce sans reçu ; le montant est obligatoire.

Un arriéré de reçus ? « + Photo » → « Choisir photo(s) ou PDF depuis les fichiers » permet d'en sélectionner plusieurs — chacun devient un reçu distinct.

────────────────────────────
INDIQUEZ QUI ÉTAIT AVEC VOUS
────────────────────────────

Sur chaque reçu, utilisez « Personnes présentes » pour noter qui était là (dîner client, taxi partagé). Votre liste est privée, vos favoris remontent en tête — et les noms apparaissent désormais à côté de la dépense dans le rapport mensuel. À faire pour chaque repas.

────────────────────────────
POURBOIRES RESTAURANT / TAXI
────────────────────────────

Pour les reçus Repas ou Taxi, un champ Pourboire apparaît : mettez le montant de l'ADDITION (tel qu'imprimé) dans Montant, choisissez un % ou un montant personnalisé, et l'application enregistre Addition + Pourboire = Total. Vos données correspondent à ce que vous avez réellement payé, l'addition imprimée restant conservée pour l'audit.

────────────────────────────
LIMITES DE DÉPENSE
────────────────────────────

Certaines catégories ont une limite par reçu fixée par l'administrateur. En cas de dépassement, le reçu est signalé — vous pouvez quand même le soumettre : touchez Confirmer sur le reçu pour indiquer que vous le savez. Rien n'est bloqué ni caché ; c'est simplement enregistré.

────────────────────────────
GÉNÉRER LE RAPPORT MENSUEL
────────────────────────────

En fin de mois, ouvrez Rapports :
  1. Choisissez le mois (par défaut le mois dernier), éventuellement une société, éventuellement une devise cible (convertie au taux du jour de capture de chaque reçu)
  2. Choisissez la langue du rapport — indépendante de la langue de l'application : vous pouvez travailler en français et remettre un PDF en anglais au comptable. Les noms d'établissements restent toujours exactement tels qu'imprimés.
  3. Touchez Générer, puis : Ouvrir le PDF, Télécharger le PDF, ou Envoyer le PDF par e-mail. Un ZIP des fichiers originaux est aussi disponible.

Rien n'est envoyé par e-mail sans que vous touchiez un bouton d'envoi.

────────────────────────────
LE BOUTON « ANOMALIES »
────────────────────────────

La pastille Anomalies du tableau de bord devient rouge quand des reçus demandent votre attention : photo illisible, montant manquant, doublon possible, valeurs modifiées par rapport au reçu, ou limite de dépense dépassée. Ouvrez chaque reçu — la bannière explique exactement pourquoi et quoi faire.

────────────────────────────
SUPPRIMÉ PAR ERREUR ?
────────────────────────────

Un reçu supprimé va dans Réglages → Corbeille pendant 30 jours. Restaurez-le depuis là ; après 30 jours, il disparaît définitivement.

────────────────────────────
PLUSIEURS ADRESSES E-MAIL ?
────────────────────────────

Si vous pouvez transférer des reçus depuis plusieurs adresses (pro + perso), répondez à cet e-mail avec les autres adresses. Elles seront enregistrées comme alias — les reçus arrivent sur le même compte et la connexion fonctionne depuis chacune.

────────────────────────────
AIDE
────────────────────────────

Aide & FAQ dans l'application (consultable, avec boîte à questions) : ${helpUrl}
Pour tout le reste : répondez simplement à cet e-mail.

— Esprey Expenses
`;
}


function welcomePt(firstName: string | null, addedBy: string | null, appUrl: string, helpUrl: string): string {
  const greeting = firstName ? `Olá ${firstName},` : "Olá,";
  const inviter = addedBy ? ` por ${addedBy}` : "";
  return `${greeting}

Foi adicionado${inviter} ao Esprey Expenses, a aplicação que usamos para registar despesas profissionais e produzir as notas de despesas mensais a reembolsar.

Guarde este e-mail como referência. Tudo o que se segue (e mais) está também na aplicação: toque no «?» no ecrã inicial para a Ajuda e FAQ pesquisável, onde também pode simplesmente fazer uma pergunta:
${helpUrl}

────────────────────────────
INICIAR SESSÃO
────────────────────────────

Abra este endereço em qualquer navegador (telemóvel, tablet, computador):
${appUrl}

Na primeira vez, a Cloudflare envia-lhe por e-mail um código único de 6 dígitos. Introduza-o e está feito. As sessões duram 24 horas; depois recebe um novo código.

Adicione a aplicação ao ecrã principal para abrir como uma aplicação nativa:
  • iPhone (Safari): toque em Partilhar → «Adicionar ao ecrã principal»
  • Android (Chrome): menu ⋮ → «Instalar aplicação»

────────────────────────────
O QUE É PRIVADO
────────────────────────────

Os seus recibos, os seus relatórios mensais, o seu perfil e dados bancários, e a sua lista privada de «pessoas» são SÓ SEUS. O administrador não vê nenhum destes elementos.

Partilhado por toda a equipa (gerido pelo administrador; vê o que lhe for atribuído): as empresas faturáveis, as categorias (e os seus limites de despesa) e as moedas.

────────────────────────────
PASSO 1: CONFIGURE O SEU PERFIL
────────────────────────────

Vá a Definições → O meu perfil e preencha:
  • O seu idioma — português, francês ou inglês. Toda a aplicação, e as descrições de recibos escritas pela IA, seguem-no.
  • O seu nome completo (e nome da empresa, se faturar através de uma)
  • Morada, número de IVA (se aplicável), telefone
  • Dados bancários — texto livre; cole o que o seu banco exigir.

Estes dados aparecem no topo de cada nota de despesas que gerar, para que o pagador saiba a quem pagar e como.

────────────────────────────
PASSO 2: TRÊS FORMAS DE ADICIONAR UM RECIBO
────────────────────────────

1) FOTO — Toque em «+ Foto» e fotografe o recibo. Fornecedor, montante, data e moeda são lidos automaticamente; confirme, etiquete, guarde.
   Fatura com várias páginas? Depois da primeira foto, toque em «+ Adicionar página» — todas as páginas são combinadas num único recibo PDF.

2) REENCAMINHAR UM E-MAIL — Envie qualquer recibo para receipts@esprey.net. Confirmações da Uber, faturas PDF, fotos, e-mails de texto: tudo funciona. IMPORTANTE: envie a partir DESTE endereço (ou de um alias registado — ver abaixo). Remetentes desconhecidos recebem uma rejeição.

3) REGISTO MANUAL — Toque em «+ Manual» para dinheiro sem recibo; o montante é obrigatório.

Recibos acumulados? «+ Foto» → «Escolher foto(s) ou PDF dos ficheiros» permite selecionar vários de uma vez — cada um torna-se um recibo distinto.

────────────────────────────
INDIQUE QUEM ESTAVA CONSIGO
────────────────────────────

Em qualquer recibo, use «Pessoas presentes» para registar quem estava (jantar com cliente, táxi partilhado). A sua lista é privada, os favoritos sobem ao topo — e os nomes aparecem junto à despesa no relatório mensal. Vale a pena fazê-lo em todas as refeições.

────────────────────────────
GORJETAS EM RESTAURANTES / TÁXIS
────────────────────────────

Nos recibos de refeições ou táxi aparece um campo Gorjeta: ponha o valor da CONTA (como impresso) em Montante, escolha uma % ou um valor personalizado, e a aplicação guarda Conta + Gorjeta = Total. Os seus registos correspondem ao que pagou realmente, com a conta impressa preservada para auditoria.

────────────────────────────
LIMITES DE DESPESA
────────────────────────────

Algumas categorias têm um limite por recibo definido pelo administrador. Se o ultrapassar, o recibo é sinalizado — pode mesmo assim submetê-lo: toque em Confirmar no recibo para registar que sabe. Nada é bloqueado nem escondido; fica apenas registado.

────────────────────────────
GERAR O RELATÓRIO MENSAL
────────────────────────────

No fim do mês, abra Relatórios:
  1. Escolha o mês (por omissão o mês passado), opcionalmente uma empresa, opcionalmente uma moeda de destino (convertida à taxa do dia de captura de cada recibo)
  2. Escolha o idioma do relatório — independente do idioma da aplicação: pode trabalhar em português e entregar um PDF em inglês ao contabilista. Os nomes dos estabelecimentos permanecem sempre exatamente como impressos.
  3. Toque em Gerar e depois: Abrir o PDF, Transferir o PDF, ou Enviar o PDF por e-mail. Um ZIP com os ficheiros originais também está disponível.

Nada é enviado por e-mail sem que toque num botão de envio.

────────────────────────────
O BOTÃO «ANOMALIAS»
────────────────────────────

O contador Anomalias no painel fica vermelho quando há recibos a precisar de atenção: foto ilegível, montante em falta, possível duplicado, valores editados diferentes do recibo, ou limite de despesa ultrapassado. Abra cada um — a faixa explica exatamente porquê e o que fazer.

────────────────────────────
ELIMINOU ALGO POR ENGANO?
────────────────────────────

Um recibo eliminado vai para Definições → Lixo durante 30 dias. Restaure-o a partir daí; após 30 dias desaparece definitivamente.

────────────────────────────
VÁRIOS ENDEREÇOS DE E-MAIL?
────────────────────────────

Se puder reencaminhar recibos de mais de um endereço (profissional + pessoal), responda a este e-mail com os outros endereços. Serão registados como alias — os recibos chegam à mesma conta e o início de sessão funciona a partir de qualquer um.

────────────────────────────
AJUDA
────────────────────────────

Ajuda e FAQ na aplicação (pesquisável, com caixa de perguntas): ${helpUrl}
Para tudo o resto: responda simplesmente a este e-mail.

— Esprey Expenses
`;
}
