// Tiny Resend client. Sends an email with one or more attachments.
// If RESEND_API_KEY isn't set the caller should skip calling this function.

export interface ResendAttachment {
  filename: string;
  bytes: Uint8Array;
}

export async function sendReportEmail(opts: {
  apiKey: string;
  fromAddress: string;       // e.g. reports@esprey.net (must be on a verified domain)
  toAddress: string;
  monthLabel: string;
  attachments: ResendAttachment[];
}): Promise<{ id: string }> {
  const summary = opts.attachments.map((a) => `- ${a.filename}`).join("\n");
  const body = {
    from: `Esprey Expenses <${opts.fromAddress}>`,
    to: [opts.toAddress],
    subject: `Expense report — ${opts.monthLabel}`,
    text:
      `Your monthly expense report for ${opts.monthLabel} is attached.\n\n` +
      `Attachments:\n${summary}\n\n` +
      `Generated by Esprey Expenses.`,
    attachments: opts.attachments.map((a) => ({
      filename: a.filename,
      content: uint8ToBase64(a.bytes),
    })),
  };
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${opts.apiKey}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Resend ${res.status}: ${txt.slice(0, 500)}`);
  }
  return (await res.json()) as { id: string };
}

/** Welcome email sent to a newly-added team member. */
export async function sendWelcomeEmail(opts: {
  apiKey: string;
  fromAddress: string;
  toAddress: string;
  displayName?: string | null;
  addedByName?: string | null;
  appUrl: string;
}): Promise<{ id: string }> {
  const greeting = opts.displayName ? `Hi ${opts.displayName.split(" ")[0]},` : "Hi,";
  const inviter = opts.addedByName ? ` by ${opts.addedByName}` : "";
  const instructionsUrl = opts.appUrl.replace(/\/$/, "") + "/instructions";
  const body = {
    from: `Esprey Expenses <${opts.fromAddress}>`,
    to: [opts.toAddress],
    subject: "You've been added to Esprey Expenses",
    text:
      `${greeting}\n\n` +
      `You've been added${inviter} to Esprey Expenses — the app we use to track business expenses and produce monthly invoices.\n\n` +
      `Sign in: ${opts.appUrl}\n` +
      `Cloudflare will email you a one-time code at this address the first time. After that, save the app to your phone's home screen (Share → Add to Home Screen on iPhone) so it works like a regular app.\n\n` +
      `Once you're in, the full instructions are on this page:\n` +
      `${instructionsUrl}\n\n` +
      `That page covers (very briefly):\n` +
      `  • What's private to you (your receipts, reports, profile, the people you tag — admins don't see these) vs. what's shared across the team (companies, categories, currencies).\n` +
      `  • The three ways to add a receipt: phone camera, manual entry, or forwarding an email to receipts@esprey.net from this address.\n` +
      `  • Setting up your profile + bank details so they appear on every monthly invoice.\n` +
      `  • Generating a monthly report (PDF invoice + ZIP of original receipts).\n\n` +
      `Have multiple email addresses you might forward from? Reply to this and I'll register them as aliases on your account so they all land in the same place.\n\n` +
      `Any issues, reply to this email.`,
  };
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${opts.apiKey}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Resend ${res.status}: ${txt.slice(0, 500)}`);
  }
  return (await res.json()) as { id: string };
}

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk) as unknown as number[]);
  }
  return btoa(binary);
}
